dataset:
  name: 'tofdc'
  root_dir: '/kunw/Dataset/TOFDC'
  input_height: 384
  input_width: 512
  min_depth: 0.1
  max_depth: 5.0

evaluation:
  do_kb_crop: false
  garg_crop: false
  eigen_crop: false
